[package]
name = "chainname-chain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
chainname-primitives.workspace = true
chainname-ghostdag.workspace = true
chainname-execution.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-evm.workspace = true
alloy-trie.workspace = true
revm.workspace = true
rayon.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
alloy-genesis.workspace = true
alloy-sol-types.workspace = true
rayon.workspace = true
proptest.workspace = true
