[package]
name = "chainname-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
chainname-primitives.workspace = true
chainname-ghostdag.workspace = true
chainname-chain.workspace = true
chainname-execution.workspace = true
chainname-pool.workspace = true
chainname-pow.workspace = true
chainname-difficulty.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-genesis.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-trie.workspace = true
alloy-evm.workspace = true
revm.workspace = true
jsonrpsee.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
parking_lot.workspace = true

[dev-dependencies]
alloy-signer.workspace = true
alloy-signer-local.workspace = true
